use maulinpa_slprod;

insert into spam_questions (question, answer, created_at, updated_at)
values
("What is the first month of the year?", "january", current_date, current_date),
("What is the second month of the year?", "feburary", current_date, current_date),
("What is the third month of the year?", "march", current_date, current_date),
("What is the fourth month of the year?", "april", current_date, current_date),
("What is the fifth month of the year?", "may", current_date, current_date),
("What is the sixth month of the year?", "june", current_date, current_date),
("What is the seventh month of the year?", "july", current_date, current_date),
("What is the eighth month of the year?", "august", current_date, current_date),
("What is the ninth month of the year?", "september", current_date, current_date),
("What is the tenth month of the year?", "october", current_date, current_date),
("What is the eleventh month of the year?", "november", current_date, current_date),
("What is the twelveth month of the year?", "december", current_date, current_date),
("The 1st month of the year is?", "january", current_date, current_date),
("The 2nd month of the year is?", "feburary", current_date, current_date),
("The 3rd month of the year is?", "march", current_date, current_date),
("The 4th month of the year is?", "april", current_date, current_date),
("The 5th month of the year is?", "may", current_date, current_date),
("The 6th month of the year is?", "june", current_date, current_date),
("The 7th month of the year is?", "july", current_date, current_date),
("The 8th month of the year is?", "august", current_date, current_date),
("The 9th month of the year is?", "september", current_date, current_date),
("The 10th month of the year is?", "october", current_date, current_date),
("The 11th month of the year is?", "november", current_date, current_date),
("The 12th month of the year is?", "december", current_date, current_date),
("What day of the week comes before Sunday?", "saturday", current_date, current_date), 
("What day of the week comes before Monday?", "sunday", current_date, current_date), 
("What day of the week comes before Tuesday?", "monday", current_date, current_date), 
("What day of the week comes before Wednesday?", "tuesday", current_date, current_date), 
("What day of the week comes before Thursday?", "wednesday", current_date, current_date), 
("What day of the week comes before Friday?", "thursday", current_date, current_date), 
("What day of the week comes before Saturday?", "friday", current_date, current_date), 
("What day of the week comes after Sunday?", "monday", current_date, current_date), 
("What day of the week comes after Monday?", "tuesday", current_date, current_date), 
("What day of the week comes after Tuesday?", "wednesday", current_date, current_date), 
("What day of the week comes after Wednesday?", "thursday", current_date, current_date), 
("What day of the week comes after Thursday?", "friday", current_date, current_date), 
("What day of the week comes after Friday?", "saturday", current_date, current_date), 
("What day of the week comes after Saturday?", "sunday", current_date, current_date);
